[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
build = "Fgc4uSFUPnhUpwUu7z4siYiBtnkxrwroYVQ2csDo3Q7P"
claim-time = "HM794G8VuTSaYv1oNGxNhxAAJVp4UoVdM1QApdT7C9UU"
labour = "BEc67x2mycQPPeWDLB8r2LCV4TSZCHTfp7rjpjwFwUhH"
repair = "FViANCSUgsHJxK3m1J2d41Yq5yJ13BDkA8eiRwQPFHuJ"
sacrifice = "85CUG48uuz6UYrvWYuDuK5Z79Q7rTGCP4y4CU933A7jd"
settlement = "ARDmmVcLaNW6b9byetukTFFriUAjpw7CkSfnapR86QfZ"
time = "AyMpNWt8uw4nEHReXXEUhbDmgmQQbfG4HZjCSkupbEne"
upgrade = "FrTthTtkfEWa2zZt4YEHGbL9Hz8hpsSW1hsHHnJXPRd4"
wait = "ECfKKquvf7PWgvCTAQiYkbDGVjaxhqAN4DFZCAjTUpwx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
