[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
assign_hero = "7gBLDn72Cog7dBvN1LWfo6W36Q7vxcv7CqYAeHwfo3Y"
assign_settlement = "42g6wojVK214btG2oUHg8vziW8UaUiQfPZ6K9kMGTCp2"
build = "fkiWK1Wn6ouGcHb3icX4XGKynef5MpsTQ478ZMdgB1g"
claim_loot = "4CjxHvNUpoCYomULBFTvmkTQPaNd9QDHPhZQ6eB9bZEf"
claim_time = "4XXA1mX5aN4Fd62FBgNxCU7FzKDYS3KSxFX3RdJYoWPj"
hero = "GBzY8ujNDb1FNkJUXUUjKV5uZPqzi6AoKsPjsqFEHCeh"
location_allocator = "J7q3dEg2KauPKkMamH9Q5FHhCoFYsSq9ramdutMpPTDc"
loot_distribution = "5F9tMTcNhgjL3tWCaF5HwLkQP9z4XJ4nTXmbYeS8UXRW"
move_hero = "6o9i5V3EvT9oaokbcZa7G92DWHxcqJnjXmCp94xxhQhv"
player = "FDY4hyNT9yaV3oXowH7u4guB2gW3Aj8psvLnGwQ9BuT6"
repair = "5xPJt6GDcmGphNAs6qU3hWAvzLwXuSqhTco6RtoAR9aY"
research = "3ZJ7mgXYhqQf7EsM8q5Ea5YJWA712TFyWGvrj9mRL2gP"
reset = "3VEXJoAZkYxDXigSWso8FnJY8z6C6inpPxU798vqc9um"
sacrifice = "6JwZJNAtkciXVGenFSoa99VBNcxyb2W8mvzcMK1vTWKs"
settlement = "5bKBE1HgusXC5jVVjpk4CvxUM8UGnVPQyvGt7cB6Jk7W"
smart-object-deity = "9RfzWgEBYQAM64a46V3dGRPKYsVY8a7YvZszWPMxvBfk"
smart-object-deity-interact = "2QPK685TLL7jUG4RYuWXZjv3gw88kUPYw7Aye63cTTjB"
smart-object-init = "64Uk4oF6mNyviUdK2xHXE3VMCtbCMDgRr1DMJk777DJZ"
smart-object-location = "5ewDDvpaTkYvoE7ZJJ9cDmZuqvGQt65hsZSJ9w73Fzr1"
token_minter = "4ZxRnucEWC62kVktmx27cz9d1PzWWNgiZLT5VWFLbfB2"
upgrade = "76wsz7SjNtvoFK8aUvojEyfjep5pMSaHQihGVxcjc1EA"
wait = "9F6qiZPUWN3bCnr5uVBwSmEDf8QcAFHNSVDH8L7AkZe4"
worker = "BExuAEwcKxKeqHSN8C1WetUAd6Tm71cZEiP8EBSrH55T"

[programs.localnet]
assign_hero = "7gBLDn72Cog7dBvN1LWfo6W36Q7vxcv7CqYAeHwfo3Y"
assign_settlement = "42g6wojVK214btG2oUHg8vziW8UaUiQfPZ6K9kMGTCp2"
build = "fkiWK1Wn6ouGcHb3icX4XGKynef5MpsTQ478ZMdgB1g"
claim_loot = "4CjxHvNUpoCYomULBFTvmkTQPaNd9QDHPhZQ6eB9bZEf"
claim_time = "4XXA1mX5aN4Fd62FBgNxCU7FzKDYS3KSxFX3RdJYoWPj"
hero = "GBzY8ujNDb1FNkJUXUUjKV5uZPqzi6AoKsPjsqFEHCeh"
location_allocator = "J7q3dEg2KauPKkMamH9Q5FHhCoFYsSq9ramdutMpPTDc"
loot_distribution = "5F9tMTcNhgjL3tWCaF5HwLkQP9z4XJ4nTXmbYeS8UXRW"
move_hero = "6o9i5V3EvT9oaokbcZa7G92DWHxcqJnjXmCp94xxhQhv"
player = "FDY4hyNT9yaV3oXowH7u4guB2gW3Aj8psvLnGwQ9BuT6"
repair = "5xPJt6GDcmGphNAs6qU3hWAvzLwXuSqhTco6RtoAR9aY"
research = "3ZJ7mgXYhqQf7EsM8q5Ea5YJWA712TFyWGvrj9mRL2gP"
reset = "3VEXJoAZkYxDXigSWso8FnJY8z6C6inpPxU798vqc9um"
sacrifice = "6JwZJNAtkciXVGenFSoa99VBNcxyb2W8mvzcMK1vTWKs"
settlement = "5bKBE1HgusXC5jVVjpk4CvxUM8UGnVPQyvGt7cB6Jk7W"
smart-object-deity = "9RfzWgEBYQAM64a46V3dGRPKYsVY8a7YvZszWPMxvBfk"
smart-object-deity-interact = "2QPK685TLL7jUG4RYuWXZjv3gw88kUPYw7Aye63cTTjB"
smart-object-init = "64Uk4oF6mNyviUdK2xHXE3VMCtbCMDgRr1DMJk777DJZ"
smart-object-location = "5ewDDvpaTkYvoE7ZJJ9cDmZuqvGQt65hsZSJ9w73Fzr1"
token_minter = "4ZxRnucEWC62kVktmx27cz9d1PzWWNgiZLT5VWFLbfB2"
upgrade = "76wsz7SjNtvoFK8aUvojEyfjep5pMSaHQihGVxcjc1EA"
wait = "9F6qiZPUWN3bCnr5uVBwSmEDf8QcAFHNSVDH8L7AkZe4"
worker = "BExuAEwcKxKeqHSN8C1WetUAd6Tm71cZEiP8EBSrH55T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs-ecs/components/*", "programs-ecs/systems/*", "programs/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[[test.genesis]]
address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
program = "tests/fixtures/dlp.so"
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/metadata.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
