[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
settlement = "5bKBE1HgusXC5jVVjpk4CvxUM8UGnVPQyvGt7cB6Jk7W"
location_allocator = "J7q3dEg2KauPKkMamH9Q5FHhCoFYsSq9ramdutMpPTDc"
hero = "GBzY8ujNDb1FNkJUXUUjKV5uZPqzi6AoKsPjsqFEHCeh"
loot_distribution = "5F9tMTcNhgjL3tWCaF5HwLkQP9z4XJ4nTXmbYeS8UXRW"
player = "FDY4hyNT9yaV3oXowH7u4guB2gW3Aj8psvLnGwQ9BuT6"
research = "3ZJ7mgXYhqQf7EsM8q5Ea5YJWA712TFyWGvrj9mRL2gP"
wait = "9F6qiZPUWN3bCnr5uVBwSmEDf8QcAFHNSVDH8L7AkZe4"
upgrade = "76wsz7SjNtvoFK8aUvojEyfjep5pMSaHQihGVxcjc1EA"
sacrifice = "6JwZJNAtkciXVGenFSoa99VBNcxyb2W8mvzcMK1vTWKs"
reset = "3VEXJoAZkYxDXigSWso8FnJY8z6C6inpPxU798vqc9um"
claim_loot = "4CjxHvNUpoCYomULBFTvmkTQPaNd9QDHPhZQ6eB9bZEf"
move_hero = "6o9i5V3EvT9oaokbcZa7G92DWHxcqJnjXmCp94xxhQhv"
assign_settlement = "42g6wojVK214btG2oUHg8vziW8UaUiQfPZ6K9kMGTCp2"
worker = "BExuAEwcKxKeqHSN8C1WetUAd6Tm71cZEiP8EBSrH55T"
claim_time = "4XXA1mX5aN4Fd62FBgNxCU7FzKDYS3KSxFX3RdJYoWPj"
assign_hero = "7gBLDn72Cog7dBvN1LWfo6W36Q7vxcv7CqYAeHwfo3Y"
build = "fkiWK1Wn6ouGcHb3icX4XGKynef5MpsTQ478ZMdgB1g"
repair = "5xPJt6GDcmGphNAs6qU3hWAvzLwXuSqhTco6RtoAR9aY"
token_minter = "4ZxRnucEWC62kVktmx27cz9d1PzWWNgiZLT5VWFLbfB2"

[programs.localnet]
assign-settlement = "GgTkjpRSLRFmw27h7uCD9Bh1MWSvKv5aPxkMjko3mxWp"
assign-worker = "F7m12a5YbScFwNPrKXwg4ua6Z9e7R1ZqXvXigoUfFDMq"
build = "AoKVKur4mczZtuzeMQwydkMe6ZSrJGxTWqZU6grPnd9c"
claim-time = "HFx2weMbr8CrAEAPfPtgw9zzgHgUFzSz7qiTyhTHGSF"
location_allocator = "DvznnhhpuH3WkBsUonUytkHhd6MYz91c2iLvRuvLeSnV"
player = "2JDZnj8f2tTvQhyQtoPrFxcfGJvuunVt9aGG8rDnpkKU"
repair = "4MA6KhwEUsLbZJqJK9rqwVjdZgdxy7vbebuD2MeLKm5j"
research = "GnVJxqk8dExpXhVidSEFNQcjTY1sCAYWcwM1GGVKKVHb"
reset = "J2HTjpKDf317Q7Pg9kUVFDregE2Ld34P61M5m4XnVSh2"
sacrifice = "4Cvjz6qrVakbSg3dqBMA8vv8XL8KD3UCTbRVM8g8WkoW"
settlement = "B2h45ZJwpiuD9jBY7Dfjky7AmEzdzGsty4qWQxjX9ycv"
upgrade = "J3evfUppPdgjTzWhhAhuhKBVM23UU8iCU9j9r7sTHCTB"
wait = "5LiZ8jP6fqAWT5V6B3C13H9VCwiQoqdyPwUYzWDfMUSy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs-ecs/components/*", "programs-ecs/systems/*", "programs/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[[test.genesis]]
address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
program = "tests/fixtures/dlp.so"
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/metadata.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
